markdown: redcarpet
pygments: true
permalink: /:title

url: "https://yuguangcan.github.io"
baseurl: ""

redcarpet:
  extensions: [strikethrough, tables]

comments :
    provider : duoshuo
    duoshuo : 
      short_name : guangcan
